version: "3.3"

services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - 80:80
    links:
      - php-fpm
    volumes:
      - ./:/var/www/laravel
      - ./docker/nginx/error_log:/var/log/nginx
  php-fpm:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/laravel
    links:
      - mysql
  mysql:
    build:
      context: ./docker/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
